[features]
seeds = false
skip-lint = false

[programs.localnet]
invoice = "8NNrnYjuajHC2jRLAaw5PYeahqRsDrRSzsZNXkTD8LES"
payout = "57aDA46BSyuGSfoW1DZLyTDTk46KatGsktGKTNzVCQ9y"
shared_wallet = "HK6ZtxWZSPjHFZWuJuvLZfKCJDB7ZEPWQe1GpMn8CVSG"
vault = "72rGhJDuuNk9ggmmRRpY3gvTSyBngWu9jCAdnpHh9fv9"

[programs.devnet]
invoice = "8NNrnYjuajHC2jRLAaw5PYeahqRsDrRSzsZNXkTD8LES"
payout = "57aDA46BSyuGSfoW1DZLyTDTk46KatGsktGKTNzVCQ9y"
shared_wallet = "HK6ZtxWZSPjHFZWuJuvLZfKCJDB7ZEPWQe1GpMn8CVSG"
vault = "72rGhJDuuNk9ggmmRRpY3gvTSyBngWu9jCAdnpHh9fv9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
